import React, { useState } from 'react';
import { Download } from 'lucide-react';
import { brands } from '../../lib/api';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import Button from './Button';

interface DownloadAllButtonProps {
  brandId: string;
  brandName?: string;
  variant?: 'button' | 'link';
  className?: string;
}

/**
 * Shared component to download all brand assets as a ZIP file
 * Used on both the Completed page and History page
 */
const DownloadAllButton: React.FC<DownloadAllButtonProps> = ({
  brandId,
  brandName = 'brand',
  variant = 'button',
  className = ''
}) => {
  const [isDownloading, setIsDownloading] = useState(false);

  const handleDownloadAll = async () => {
    try {
      setIsDownloading(true);

      // Fetch all assets
      const response = await brands.listAssets(brandId);
      const assets = response.assets;

      if (!assets || assets.length === 0) {
        alert('No assets available to download');
        return;
      }

      // Fetch full content for each asset
      const assetContents: { [key: string]: any } = {};
      for (const asset of assets) {
        try {
          const fullAsset = await brands.getAsset(brandId, asset.id);
          assetContents[asset.type] = fullAsset;
        } catch (error) {
          console.error(`Failed to load asset ${asset.type}:`, error);
        }
      }

      // Create ZIP file
      const zip = new JSZip();
      const brandFolder = zip.folder(brandName);

      if (!brandFolder) {
        console.error('Failed to create folder in ZIP');
        alert('Failed to create ZIP archive. Please try again.');
        return;
      }

      // Add each asset to the ZIP
      for (const [assetType, asset] of Object.entries(assetContents)) {
        if (asset && asset.content) {
          let fileExtension = '.txt';
          let fileName = assetType.replace(/_/g, '-');

          // Check if content is JSON
          try {
            const parsed = JSON.parse(asset.content);
            fileExtension = '.json';
            brandFolder.file(`${fileName}${fileExtension}`, JSON.stringify(parsed, null, 2));
          } catch {
            // Not JSON, determine extension based on content
            if (asset.content.includes('http') && asset.content.includes('\n')) {
              fileExtension = '.txt';
            } else if (asset.content.includes('#') && asset.content.includes('rgb')) {
              fileExtension = '.css';
            }
            brandFolder.file(`${fileName}${fileExtension}`, asset.content);
          }

          // Add metadata if available
          if (asset.description) {
            brandFolder.file(`${fileName}-info.txt`, `Type: ${assetType}\nDescription: ${asset.description}\n`);
          }
        }
      }

      // Add README file
      const readme = `${brandName} - Brand Package
${'='.repeat(50)}

Generated by Brandician AI
Date: ${new Date().toLocaleDateString()}

This package contains all your brand assets.

Contents:
${assets.map(asset => `- ${asset.type.replace(/_/g, ' ')}`).join('\n')}

Thank you for using Brandician AI!
Visit https://brandician.ai for more information.
`;
      brandFolder.file('README.txt', readme);

      // Generate and download ZIP
      const zipBlob = await zip.generateAsync({ type: 'blob' });
      saveAs(zipBlob, `${brandName}-brand-assets.zip`);
    } catch (error) {
      console.error('Failed to create ZIP archive:', error);
      alert('Failed to create ZIP archive. Please try again.');
    } finally {
      setIsDownloading(false);
    }
  };

  if (variant === 'link') {
    return (
      <button
        onClick={handleDownloadAll}
        disabled={isDownloading}
        className={`inline-flex items-center text-sm font-medium text-primary-600 hover:text-primary-700 disabled:opacity-50 disabled:cursor-not-allowed ${className}`}
      >
        <Download className={`h-4 w-4 mr-1 ${isDownloading ? 'animate-spin' : ''}`} />
        {isDownloading ? 'Preparing...' : 'Download all'}
      </button>
    );
  }

  // Default button variant using Button component
  return (
    <Button
      onClick={handleDownloadAll}
      disabled={isDownloading}
      size="lg"
      className={className}
      leftIcon={<Download className={`h-5 w-5 ${isDownloading ? 'animate-spin' : ''}`} />}
    >
      {isDownloading ? 'Preparing...' : 'Download All'}
    </Button>
  );
};

export default DownloadAllButton;
